### ISSUE TITLE
Empecher l'utilisateur de se désactiver lui-même

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/ci_packbase_hmvc#10]
Un utilisateur admin ne devrait pas pouvoir se désactiver ou se supprimer lui même.

**Comment by DidierViret** [comment]
Repartir de la branche master pour corriger ce fonctionnement de la manière suivante :

- Si un admin essaie de se désactiver ou se supprimer lui-même, afficher la vue "delete" avec un message d'erreur (alert alert-danger) "Vous ne pouvez pas désactiver ou supprimer votre propre compte. Cette opération doit être faite par un autre administrateur.".
- Si un admin modifie son propre compte (vue "form"), la liste déroulante "Type d'utilisateur" doit être désactivée et grisée et un message d'information doit être affiché (alert alert-info) "Vous ne pouvez pas modifier votre propre type d'utilisateur. Cette opération doit être faite par un autre administrateur.".
