### ISSUE TITLE
Appliquer les conventions définies

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/ci_packbase_hmvc#16]
CodeIgniter a ses propres conventions de nommage [dans la documentation](https://codeigniter.com/user_guide/general/styleguide.html).
Ces conventions ne sont pas toutes actuellement appliquées dans nos applications. Il faut voir si c'est possible de les appliquer sans problèmes majeurs.

**Comment by DidierViret** [comment]
A appliquer pour les nouveaux développements mais ne pas corriger l'ensemble du code pour qu'il respecte ces conventions.
