### ISSUE TITLE
Utiliser un token au lieu d'un mot de passe pour le support

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/ci_packbase_hmvc#17]
Hi @Orif-support,

You recently used a password to access an endpoint through the GitHub API using PHP-Server. We will deprecate basic authentication using password to this endpoint soon:

https://api.github.com/repositories/66556272/issues

We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

Thanks,
The GitHub Team

**Comment by DidierViret** [comment]
Modification implémentée dans le module support.
