### ISSUE TITLE
Considérer l'utilisation du HMVC par N3Cr0N

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/ci_packbase_hmvc#2]
[Le HMVC de N3Cr0N](https://github.com/N3Cr0N/HMVC) était mis à jour jusqu'il y a 5 mois. La version de HMVC du projet date de plus de 3 ans.

L'autre solution serait de créer un projet dédié à un HMVC pour le reste des projets.

**Comment by DidierViret** [comment]
Bonne idée, j'ai fait un fork de cette version pour en garder une copie "en lieu sûr". Nous allons nous baser sur cette version pour nos projets.

**Comment by DidierViret** [comment]
Version N3Cr0N reprise dans le ci_packbase_hmvc
