### ISSUE TITLE
Les controllers sans module héritent aussi de MX_Controller

### ISSUE THREAD

**Issue by BurkhalterY** [OrifInformatique/ci_packbase_hmvc#26]
MY_Controller hérite toujours de MX_Controller alors qu'il y a encore des controllers sans module dans certaines de nos applications.
Il faudrait vérifier que ça ne pause pas de problème d'avoir un controller simple qui hérite de MX_Controller.

**Comment by DidierViret** [comment]
Bonne remarque, mais apparemment tout fonctionne bien dans gestion_questionnaires qui contient des modules et des contrôleurs hors modules.
A surveiller si un problème est constaté dans le futur.
