### ISSUE TITLE
Textes de boutons réutilisables

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_hmvc#4]
Pour permettre d'utiliser le même texte dans plusieurs boutons, remplacer le texte du bouton "Ajouter un utilisateur" par "Nouveau".

Dans le fichier MY_admin_lang, supprimer btn_add_user et ajouter 2 textes :
- btn_add_m = "Nouveau"
- btn_add_f = "Nouvelle"

**Comment by MestourBS** [comment]
Fait dans le commit d06bc23
