### ISSUE TITLE
Affichage des utilisateurs désactivés

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_hmvc#5]
Faire en sorte que la liste d'administration des utilisateurs n'affiche que les utilisateurs actifs.

Ajouter une case à cocher à la même hauteur que le bouton "Nouveau" mais tout à droite de l'écran, avec comme texte "Afficher les utilisateurs désactivés". Si cette case est cochée, les utilisateurs désactivés doivent apparaître dans la liste.

Lorsqu'on modifie cette case à cocher, la liste doit être rafraichie automatiquement (JQuery ou PHP ?).

**Comment by MestourBS** [comment]
Réglé dans le commit d06bc23
La liste est rafraishie avec PHP
