### ISSUE TITLE
Branche AdminModule - nouvel utilisateur

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/ci_packbase_hmvc#7]
Si on ouvre le formulaire pour la création d'un nouvel utilisateur, on choisi le nom et le type d'utilisateur, on clique sur Enregistrer alors qu'il y a une erreur dans le mot de passe. Le message d'erreur s'affiche correctement mais les champs nom et type d'utilisateur sont remis à zéro alors qu'ils devraient conserver leurs valeurs.

**Comment by MestourBS** [comment]
Réglé dans ba16682
